kind: pipeline
name: default
type: docker

steps:
  - name: generate-readme
      image: eclipse-temurin:17
      commands:
        - ./gradlew --info --stacktrace --no-daemon --build-cache clean run
      environment:
        GRADLE_USER_HOME: /drone/src/.gradle-cache
        DEVSOAP_GRADLE_CACHE_EMAIL:
          from_secret: DEVSOAP_GRADLE_CACHE_EMAIL
        DEVSOAP_GRADLE_CACHE_KEY:
          from_secret: DEVSOAP_GRADLE_CACHE_KEY

  - name: publish
      image: drone/git
      commands:
        - git diff -U0
        - git commit -am "Updated Readme"
        - git push origin master
      environment:
        GITHUB_USERNAME:
          from_secret: GITHUB_USERNAME
        GITHUB_PUSH_TOKEN:
          from_secret: GITHUB_PUSH_TOKEN

trigger:
  branch:
    - master